# credentials:
#   usernames:
#     jsmith:
#       email: jsmith@gmail.com
#       name: 7512301
#       password: $2b$12$Y0KSeMFSHSp.rZw1SlWeHOkVz0v56z4k/rN1WzCKV68hdhPWnKbWC  # To be replaced with hashed password
#     tony:
#       email: rbriggs@gmail.com
#       name: 7561459
#       password: $2b$12$Y0KSeMFSHSp.rZw1SlWeHOkVz0v56z4k/rN1WzCKV68hdhPWnKbWC # To be replaced with hashed password
# cookie:
#   expiry_days: 30
#   key: random_signature_key # Must be string
#   name: random_cookie_name
# preauthorized:
#   emails:
#   - melsby@gmail.com

credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      logged_in: True # Will be managed automatically
      name: 7512301
      password: $2b$12$Y0KSeMFSHSp.rZw1SlWeHOkVz0v56z4k/rN1WzCKV68hdhPWnKbWC
       # Will be hashed automatically
    rbriggs:
      email: rbriggs@gmail.com
      logged_in: False # Will be managed automatically
      name: 7561459
      password: $2b$12$Y0KSeMFSHSp.rZw1SlWeHOkVz0v56z4k/rN1WzCKV68hdhPWnKbWC # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com